"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var v1 = "Hello!";
var v2 = 10;
var v3 = 10.9996;
var v4 = true;
var v5 = "Welcome";
var v6;
const msg = "Welcome to TypeScript";
v6 = 2017;
console.log("TypeOf v1 = " + (typeof v1) + ",  value = " + v1);
console.log("TypeOf v2 = " + (typeof v2) + ",  value = " + v2);
console.log("TypeOf v3 = " + (typeof v3) + ",  value = " + v3);
console.log("TypeOf v4 = " + (typeof v4) + ",  value = " + v4);
console.log("TypeOf v5 = " + (typeof v5) + ",  value = " + v5);
console.log("TypeOf v6 = " + (typeof v6) + ",  value = " + v6);
v6 = "Cypress";
console.log("TypeOf v6 = " + (typeof v6) + ",  value = " + v6);
console.log("Const Msg = " + msg);
